---
title: "ANTH 102 Syllabus"
author: "Mt. Hood Community College"
date: "Winter 2016"
output:
  html_document:
    theme: united
---

## General Course Information

- **Course ID:**  ANTH102, Section W1
- **Course Title:** Introduction to Archaeology and World Prehistory
- **Course Location:** Online (Blackboard)
- **Credits:** 4
- **Pre-requisites:** RD90 and WR90


## Instuctor Contact Information

- **Name:** Trey Batey
- **MHCC email:** <trey.batey@mhcc.edu>
- **MHCC voicemail:** 503-491-6245 (ext. 3441)
- **MHCC Office Hours:** None (virtual office only)

The best way to get in touch with me is through MHCC email. You can send me messages through Blackboard's "Mailbox" system, as well, but in my experience, this tool is clunky. I typically check email at least once a day and check my messages each time I log in to Blackboard. Unless circumstances prevent me from doing so, I will respond to messages within 48 hours, typically within 24.


## Required Materials
 
In order to keep students' costs down, I am not requiring a textbook for this course. If you would like to obtain a copy of an introductory archaeology/world prehistory textbook (for your own reference), there are many to choose from, and they can be found through any number of retailers (e.g., <a href="https://www.amazon.com/s/ref=nb_sb_noss?url=search-alias%3Daps&field-keywords=archaeology+world+prehistory" target="_blank">amazon.com</a>, <a href="http://www.chegg.com/search/archaeology%20world%20prehistory/federated?trackid=53a516b4&strackid=2cde90e3&event=enter_submit#p=1" target="_blank">chegg.com</a>, <a href="http://www.textbooks.com/Search.php?TYP=SBJ&dHTxt=archaeology+world+prehistory&mHTxt=&CSID=A2UTJ2OQ3KJWDQD2MUQDM2SOB&PART=PRINT&TXT=archaeology+world+prehistory" target="_blank">textbooks.com</a>). In previous terms of this course, I've used the following books:

- Chazan, M. 2014. _World history and archaeology: pathways through time, 3rd edition_. New Jersey: Prentice Hall (Pearson Education, Inc.).

- Fagan, B. 2011. _Ancient lives: an introduction to archaeology and prehistory, 5th edition_. New York: Routledge.
 
A cost-effective alternative to printed versions is obtaining textbooks in digital format. The MHCC Bookstore [provides information](http://www.bookstore.mhcc.cc.or.us/about_jumpbooks.asp?)---FAQ's, recommended computer requirements, etc.---on accessing textbooks online or downloading them for use offline.

The content of this course, while not dependent on a textbook, does follow a similar order and presents much of the same information available in typical introductory archaeology/prehistory texts. 


## Attendance/Participation
 
* You should log into the course on the __first day__ of classes.
* Before you can access any lessons, you must do the following:
    + Review the syllabus and schedule and mark them as "Reviewed,"
    + take a short survey,
    + post to a discussion forum for introductions, and
    + take a short quiz to familiarize yourself with Blackboard's testing system.
  
After you have completed those steps, you will have access to the course content, as it becomes available. __I expect students to login and actively participate in the course throughout the term.__ To see how a typical weekly lesson may look, see the sample weekly schedule below.

### Sample Weekly Schedule
Typically, new content will be released at midnight on Tuesdays. Thus, you will have a full week to complete _all_ assignments for a particular lesson, with assignments due by the end of the day (i.e., 11:59 PM) on Mondays. __Please don't fall into the trap of waiting until Monday night to begin working on assignments.__ Some assignments, specifically discussion activities, require you to submit the minimum number of posts---generally two---on separate days. So, in these instances, waiting until Monday to submit all your posts would result in a loss of points. The table below is an example of the work-flow for a typical week.

Tues. | Wed. | Thurs. | Fri. | Sat. & Sun. | Mon.
----- | ---- | ------ | ---- | ---------- | ----
Begin looking at new lesson content | Continue looking at content; submit first discussion post | Continue looking at content; __deadline to submit initial thread post to discussion forum__ | Work on additional activities; maybe submit second discussion (response) post | Work on additional activities; submit at least one of two required response posts to discussion forum; take quiz | __Deadline to submit quiz, secondary response posts to discussion forum, and any other assignments__


## Communication Guidelines
 
I will make "all-class" communications through Blackboard's Announcements tool, accessible in the left-side menu and, also, from the Dashboard.

For students:

- If you have a _general_ question about the class (e.g., content, technology issues...), create a discussion thread in the SOS discussion forum. If you are unsure about something or having some technical issue, there is a good chance that others are, too.  The SOS discussion forum allows everyone to see questions and answers.

- If you have a question _specifically_ about _your_ assignment (e.g., grade, feedback), please contact me directly via email or Blackboard's message system.

- Even though we live in a text-message (or Tweet-) world, when it comes to spelling/grammar, please keep all discussion posts and other messages (semi-)formal. __Please limit the use of abbreviations. In other words, write as if we were speaking in a face-to-face setting.__

- Be to the point, and please keep all discussion posts relevant to the forum subject. Most of all, please keep __ALL__ posts polite and respectful. Check these [general guidelines for etiquette](http://online.uwc.edu/technology/etiquette) in an online learning environment. In advance, thank you.

- For more information, see please see the [MHCC Internet Privacy policy](http://www.mhcc.edu/privacy.aspx).


## Student Responsibilities
 
Since this is an introductory course, the material has more breadth than depth. To better understand more abstract concepts, you have to understand at least the basic jargon (terminology) used in the field of anthropology and sub-field of archaeology. Background readings, slideshows, and online resources are meant to expose you to terms and concepts with which you need to become familiar. For example, let's say you have an assignment to address the following questions in a Discussion forum:
 
> What are some examples of natural and cultural transformation processes that affect archaeological sites? How could any one or more of these bias archaeological interpretations?
 
Before you can comment on this question, you need to know what a _transformation process_ is, as it relates to archaeology. Thus, your performance in the discussions assumes that you keep current with the readings and other course material.
 
### Discussion Forum Requirements
Participation is essential in an online learning environment. This applies especially to discussion forums, which require __regular participation over the course of each week__. Discussion forums have the following general participation requirements and weekly deadlines:

- Submit an initial thread addressing a question (or questions) provided in the assignment directions by the instructor (Thursday, 11:59 PM).
- Submit at least two posts in response to the initial thread of at least two different classmates.
- Discussion posts (i.e., initial thread and required response posts) must be submitted on *at least three different days*.

Consistent participation in discussion activities will help determine your learning outcomes and your grade. 



## Grades
 
Letter grades are based on MHCC's, 10-point scale (as they relate to one's grade point average, or GPA):  100-90% = A, 89-80% = B, 79-70% = C, 69-60% = D, and below 60% = F). All graded activities (lesson activities, quizzes, discussions, etc.) are graded with a point-to-percent system (i.e., percent grade = points earned/points possible). Your final grade, though, is determined by a __weighted average__ (see grading table below) of the different types of activities. For example, your average for discussion assignments counts for 30% of the final grade, so it is essential that you participate in all discussion activities.

### Grading Table

Assignment Type | Percent of Final Grade
--------------- | ----------------------
Discussions (7--8) | 30%
Quizzes (9--10) | 25%
Miscellaneous lesson activity (2--3) | 20%
Midterm exam | 12.5%
Final exam | 12.5%
__Total__ | __100%__


## Late Work Policy

Late-work is accepted, but there are caveats...

- No credit will be given for discussion activities in which all posts are submitted after the due date.
- Quizzes and any other (non-discussion) assignments will be penalized the point-equivalent of a letter grade for each day late. __These assignments will not be accepted if submitted more than five (5) days late.__
- __Exams will NOT be accepted late.__  
 
 
## Resources for Students
 
Since you pay for it, take advantage of the MHCC's resources. Many great resources to help students succeed are available at the <a href="http://www.mhcc.edu/lsc/" target="_blank">MHCC Learning Success Center</a>, including resources for the following:

- [Computer help](http://www.mhcc.edu/StudentServices.aspx?id=404)

- [Study skills/time management](http://www.mhcc.edu/StudentServices.aspx?id=403)

- [English Language Learners (ELL)](http://www.mhcc.edu/StudentServices.aspx?id=400)
 
Finding information is essential for research. The [MHCC Library](http://www.mhcc.edu/Library.aspx) is a great source of many useful tools, including tutorials on how to find books and articles. For example, you may need to search a social science database to find an article about prehistoric human migration to the Western Hemisphere. Tutorials also provide in information on how to avoid plagiarism. For more information, see [MHCC's Student Code of Conduct](http://www.mhcc.edu/coc/).

 
## Additional Information
 
The <a href="http://home.mhcc.edu/office_of_instruction/pdf%20forms/syllabus_addendum_Gresham_Bruning.pdf" target="_blank">MHCC Syllabus Addendum</a> contains additional information on Disability Services, Academic Integrity, and other important stuff.
