---
title: 'Lesson 7 Discussion:  Just Eat It!'
author: "ANTH 102-W1---Fall 2014"
output:
  html_document:
    fig_caption: yes
    theme: united
---

In this discussion activity, students will ponder what the archaeological evidence suggests about variation in plant/animal domestication and developments in social complexity around the world.

### Instructions
After going through the lesson content, including textbook readings, slideshow, and other electronic resources, create an initial thread and respond to the following: 

- Choose a specific region/site discussed in the textbook readings or supplemental material. __What information did you find most interesting about...__
    + the particular plants/animals domesticated there?
    + evidence for developments in social complexity there?
    
- On a separate day than your original post, return to the discussion forum and submit a response to at least one classmate's original thread post. After that, feel free to comment as you like.

### Evaluation Criteria
You will be evaluated on the following:

- Content: There is no required word count, _per se_, but you must adequately address the questions posed and provide a meaningful, well-thought response. Did you answer the discussion question (and reply) with a thoughtful response that includes references to material presented in the lecture, readings, and/or web-readings?

- Grammar/style: Did you use proper grammar and style (spelling, complete sentences…) making your post easy to understand?

- Participation: Did you submit the required number of posts. Initial thread and response post must be made on separate days. [I suggest submitting your initial thread by Thursday (at the latest) and your response post one/two days later. You may submit more than one response post.]

- Follow the general guidelines of discussion etiquette (see Syllabus).

### Getting Started
To prepare for this discussion, you should watch the lecture slideshow and, assuming you have the textbook, skim through the supplemental readings.

Access the Discussion Forum, "Just Eat It!,” and follow the instructions above. __For this activity, you must first submit your intial thread _before_ you can view/respond to other posts.__

Remember, you must make your second discussion post on a different date than your original post.

-----

#### Continue
__Be sure to mark this page as “reviewed.”__ Then, go to the next page to access a link to the discussion forum. If the forum does not automatically open in a new window, click “Click to Launch.”