---
title: "Lesson 2 Discussion:  How to Archaeologize"
author: "ANTH 102-W1---Fall 2014"
output:
  html_document:
    fig_caption: yes
    theme: united
---

Over the next couple lessons, we'll be considering the "how to" of archaeology: (1) how archaeologists recover their data, (2) how they classify and analyze it, and (3) the theoretical approaches they use to help the data tell a story of past human activity and other less-tangible aspects of human behavior.


### Instructions
After going through the lesson content, including textbook readings, slideshow, and other electronic resources, create an initial thread and respond each of the following: 

- What did you find most interesting and/or surprising regarding the process of archaeological research? __Why?__
    
- Imagine you are working at any archaeological site. What natural and cultural factors may affect the state in which we find archaeological sites and how may that affect our interpretations of the past?


### Evaluation Criteria

You will be evaluated using the same criteria as other discussion activities:

- Content: There is no required word count, _per se_, but you must adequately address the questions posed and provide a meaningful, well-thought response. Did you answer the discussion question (and reply) with a thoughtful response that includes references to material presented in the lecture, readings, and/or web-readings?

- Grammar/style: Did you use proper grammar and style (spelling, complete sentences€¦) making your post easy to understand?

- Participation: Did you submit the required number of posts. Initial thread and response posts must be made on three separate days. [Students must submit their initial threads by the end-of-day Thursday (at the latest) and your response posts should come over the rest of the week. You may submit more than the minimum required.]

- Follow the general guidelines of discussion etiquette (see Syllabus).


### Getting Started
To prepare for this discussion, you should watch the lecture slideshow and, assuming you have the textbook, skim through the supplemental readings.

- Go to the next page to access the Discussion Forum link, "How to Archaeologize" and address the questions in the instructions above.


-----

#### Continue
__Be sure to mark this page as "reviewed."__ Then, go to the next page to access a link to the discussion forum. If the forum does not automatically open in a new window, click "€œClick to Launch."