---
title: "Lesson 6 Discussion:  Agricultural Origins (Open Forum)"
author: "ANTH 102-W1"
date: "Spring 2015"
output:
  html_document:
    fig_caption: yes
    theme: united
---

This discussion activity is an open forum. This does not mean that you may discuss anything. Topics/comments should relate to the content of *this lesson*: archaeological (anthropological) research into the origins of plant and animal domestication, specifically in the region of the Levant ("Fertile Crescent"), and associated aspects of developing social complexity.



### Instructions
To successfully participate in and complete this discussion activity, you will need to do the following:

1. After going through the lesson content, including textbook readings, slideshow, and other electronic resources, create an initial thread and respond to the following:  __What did you find most interesting/strange/confusing/ect. about this material in this lesson? Why?__
    
2. Return to the discussion forum throughout the week and submit a response to at least two classmates' original thread posts. After that, feel free to comment as you like. *Remember, the minimum required submissions must be submitted on three separate days.*


### Evaluation Criteria

You will be evaluated using the same criteria as other discussion activities:

- Content: There is no required word count, _per se_, but you must adequately address the questions posed and provide a meaningful, well-thought response. Did you answer the discussion question (and reply) with a thoughtful response that includes references to material presented in the lecture, readings, and/or web-readings?

- Grammar/style: Did you use proper grammar and style (spelling, complete sentences€¦) making your post easy to understand?

- Participation: Did you submit the required number of posts (3). Initial thread and response posts must be made on *three separate days*. [Students must submit their initial threads by the end-of-day Thursday (at the latest) and your response posts should come over the rest of the week. You may submit more than the minimum required.]

- Follow the general guidelines of discussion etiquette (see Syllabus).


### Getting Started

Before you create that first thread...

1. Prepare for this discussion. You should watch the lecture slideshow, read over the selected textbook content, and check out some of the supplemental online content.

2. Access the Discussion Forum, "Agricultural Origins (Open Forum)," and follow the instructions above.

<br>

-----
#### Continue
__Be sure to mark this page as "reviewed."__ Then, go to the next page to access a link to the discussion forum. If the forum does not automatically open in a new window, click "€œClick to Launch."