---
title: "Lesson 8 Discussion:  I'm in a City-State of Mind"
author: "ANTH 102-W1"
date: "Spring 2015"
output:
  html_document:
    fig_caption: yes
    theme: united
---

In this discussion activity, students will reflect upon the differences (and any similarities) in how state-level organization developed in Mesopotamia, Egypt, and the Aegean.

### Instructions
After going through the lesson content, including textbook readings, slideshow, and other electronic resources, create an initial thread and respond to the following: 

- _Concisely_ compare and contrast the emergence of state-level social organization developed in Mesopotamia, Egypt, and the Aegean.
    + Your analysis should include the major factors, discussed in the textbook, slideshow, and/or other resources that affected the process in these regions.
    + Did you notice in similarities in state-formation in these regions?
    
- Was there anything, in particular, that you found fascinating about the content in this lesson---either in the textbook, slideshow, or links to additional resources?
    
Next, throughout the week, return to the discussion forum and submit a response to at least two classmates' original threads. After that, feel free to comment as you like.


### Evaluation Criteria
You will be evaluated on the following:

- Content: There is no required word count, _per se_, but you must adequately address the questions posed and provide a meaningful, well-thought response. Did you answer the discussion question (and reply) with a thoughtful response that includes references to material presented in the lecture, readings, and/or web-readings?

- Grammar/style: Did you use proper grammar and style (spelling, complete sentencesÄ¶) making your post easy to understand?

- Participation: Did you submit the required number of posts (3). Initial thread and response posts must be made on *three separate days*. [Students must submit their initial threads by the end-of-day Thursday (at the latest) and your response posts should come over the rest of the week. You may submit more than the minimum required.]

- Follow the general guidelines of discussion etiquette (see Syllabus).


### Getting Started
To prepare for this discussion, you should watch the lecture slideshow and, assuming you have the textbook, skim through the supplemental readings.

Access the Discussion Forum, "I'm in a City-State of Mind" ù and follow the instructions above. __For this activity, you must first submit your intial thread _before_ you can view/respond to other posts.__

<br>

-----
#### Continue
__Be sure to mark this page as "reviewed."__ Then, go to the next page to access a link to the discussion forum. If the forum does not automatically open in a new window, click "ÄúClick to Launch."