---
title: "Quiz Info"
author: "ANTH 102-W1"
date: "Spring 2015"
output:
  html_document:
    fig_caption: yes
    theme: united
---

After this lesson, you should have a better understanding of how state-level organization developed in Mesopotamia, Egypt, and the Aegean. This quiz focuses on some of the highlights (factoids) from Lesson 8.


### What content is covered?
This quiz reviews the terms and concepts contained in this lesson:  

- how archaeologists define _cities_, _states_, and the archaeological evidence for these things that they try to find; 
- the circumstances surrounding the development of state-level organization in the regions of Mesopotamia, Egypt, the Aegean.

### Quiz Environment
This quiz is not proctored, and there is no time limit. You may use the lecture slideshow, textbook, and any other online resources provided to help you answer the questions. This quiz may only be taken once.

### Availability
The Lesson 8 Quiz will be available Friday and is due by the end of the day Monday. [Remember, you can always check due dates by clicking on the My Grades button in the left-side menu.]

<br>

----
#### Continue

Go to the next page to access the Lesson 8 Quiz link (available 20 November).