---
title: "Quiz Info"
author: "ANTH 102-W1"
date: "Spring 2015"
output:
  html_document:
    fig_caption: yes
    theme: united
---

After this lesson, you should have a better understanding of the archaeological evidence for the development of social complexity, including state-organized societies, in the Americas---well, at least in the places where we know them to have developed:  Mesoamerica and the Andean region of South America. This quiz focuses on some of the highlights (factoids) from Lesson 10.


### What content is covered?
This quiz reviews the terms and concepts contained in this lesson:  

- the development of different cultures and state-level societies in Mesoamerica (e.g., Maya, Toltec, Aztec...).
- the development of different cultures and state-level societies in Andean South America (e.g., Chavin de Huantar, Moche, Tiwanaku, Wari, Inca...).


### Quiz Environment
This quiz is not proctored, and there is no time limit. You may use the lecture slideshow, textbook, and any other online resources provided to help you answer the questions. This quiz may only be taken once.

### Availability
The Lesson 10 Quiz will be available __*Thursday*__ and must be completed by the end of the day __*Sunday*__. [__Please note the slightly different start/due dates for this week's quiz, as they have been modified since this is the week prior to finals week.__ Remember, you can always check due dates by clicking on the My Grades button in the left-side menu.]

----

#### Continue

Go to the next page to access the Lesson 10 Quiz link (available 3 December).